# Generated by Django 5.0.4 on 2024-06-23 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('duration_in_days', models.PositiveIntegerField(null=True, unique=True, verbose_name='Duration in Days')),
                ('estimated_hours', models.FloatField(null=True, unique=True, verbose_name='Estimated Hours')),
                ('start_date', models.DateField(default=datetime.date(2024, 6, 23), null=True, unique=True, verbose_name='Start Date')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
