# Generated by Django 5.0.4 on 2024-06-27 17:56

from django.db import migrations


def add_price(apps, schema_editor):
    MULTIPLIER = 120

    smart_phones_models = apps.get_model('main_app', 'Smartphone')

    all_smart_phones = smart_phones_models.objects.all()

    for phone in all_smart_phones:
        phone.price = len(phone.brand) * MULTIPLIER

    smart_phones_models.objects.bulk_update(all_smart_phones, ['price'])


def add_category(apps, schema_editor):
    smart_phones_models = apps.get_model('main_app', 'Smartphone')

    all_smart_phones = smart_phones_models.objects.all()

    for phone in all_smart_phones:
        if phone.price < 750:
            phone.category = 'Cheap'
        else:
            phone.category = 'Expensive'

    smart_phones_models.objects.bulk_update(all_smart_phones, ['category'])


def add_category_and_price(apps, schema_editor):
    add_price(apps, schema_editor)
    add_category(apps, schema_editor)


def reverse_category_and_price(apps, schema_editor):
    smart_phones_models = apps.get_model('main_app', 'Smartphone')

    all_smart_phones = smart_phones_models.objects.all()

    for phone in all_smart_phones:
        phone.price = smart_phones_models._meta.get_field('price').default
        phone.category = smart_phones_models._meta.get_field('category').default

    smart_phones_models.objects.bulk_update(all_smart_phones, ['price', 'category'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(add_category_and_price, reverse_category_and_price),
    ]
